services:
  message-broker:
    build:
      context: .
      dockerfile: Dockerfile
      network: host
    env_file:
      - ./.env
    ports:
      - "7000:7000"
    environment:
      - HOST=localhost:7000
      - TOPICS
    networks:
      - message-broker-network

networks:
  message-broker-network:
    driver: bridge
